name: MT6765 Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl zip build-essential bc bison flex \
          libssl-dev libelf-dev python3 python3-pip wget

      - name: Fix python2 (IMPORTANT FOR MTK)
        run: |
          sudo ln -sf $(which python3) /usr/bin/python2
          python2 --version || true

      - name: Clone toolchains
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc32
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git AnyKernel

      - name: Build kernel
        run: |
          export KERNEL_DIR=$PWD
          export ARCH=arm64
          export SUBARCH=arm64

          export PATH=$PWD/clang/bin:$PWD/gcc/bin:$PWD/gcc32/bin:$PATH

          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-

          export CC=clang
          export LD=ld.lld
          export LLVM=1
          export LLVM_IAS=1
          export LDFLAGS="-fuse-ld=lld"

          echo "===================="
          echo "Defconfig"
          echo "===================="

          make O=out ARCH=arm64 2e_defconfig

          echo "===================="
          echo "Build kernel"
          echo "===================="

          make -j$(nproc) O=out ARCH=arm64 \
            CC=clang LLVM=1 LLVM_IAS=1

          echo "===================="
          echo "Modules"
          echo "===================="

          make -j$(nproc) O=out ARCH=arm64 modules

      - name: Package AnyKernel
        run: |
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/ || true
          cp out/arch/arm64/boot/Image AnyKernel/ || true

          cd AnyKernel
          zip -r9 Kernel.zip *
          cd ..

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-MT6765
          path: AnyKernel/Kernel.zip
